apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bdd-donnees-mysql
  namespace: sld07-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # StorageClass par défaut recommandé, ou spécifier (ex: ceph-rbd)