apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: image-fedora-bdd
  namespace: saliou-diop-dev
spec:
  source:
    http:
      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm2-serveur-bdd
  namespace: saliou-diop-dev
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm2-serveur-bdd
    spec:
      domain:
        devices:
          disks:
            - name: boot
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: mysql-data
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 1Gi
            cpu: 2
      networks:
        - name: default
          pod: {}
      volumes:
        - name: boot
          dataVolume:
            name: image-fedora-bdd
        - name: mysql-data
          persistentVolumeClaim:
            claimName: bdd-donnees-mysql
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: serveur-bdd
              user: fedora
              password: "Password123!"
              chpasswd: { expire: False }
              ssh_pwauth: True
              packages:
                - mariadb-server
              runcmd:
                - systemctl enable --now mariadb