apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm2-serveur-bdd
  namespace: saliou-diop-dev
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: image-fedora-bdd
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 5Gi
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm2-serveur-bdd
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: boot
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: mysql-data
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      tolerations:
        - effect: NoSchedule
          key: sandbox-cnv
          operator: Exists
      volumes:
        - name: boot
          dataVolume:
            name: image-fedora-bdd
        - name: mysql-data
          persistentVolumeClaim:
            claimName: bdd-donnees-mysql
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: serveur-bdd
              user: fedora
              password: "Password123!"
              chpasswd: { expire: False }
              ssh_pwauth: True
              packages:
                - mariadb-server
              runcmd:
                - systemctl enable --now mariadb