apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: saliou-diop-dev
data:
  # 1. Le code de ton application Node.js (qui va se connecter à la DB)
  app.js: |
    const express = require('express');
    const mysql = require('mysql2');
    const app = express();
    const port = 3000;

    app.get('/', (req, res) => {
        res.send(`
            <h1>🚀 Félicitations ! L'application fonctionne !</h1>
            <p>L'application Node.js est bien cachée derrière Nginx.</p>
            <p>La base de données cible est : <strong>${process.env.DB_HOST}</strong></p>
        `);
    });

    app.listen(port, () => {
        console.log(`Serveur Node.js démarré sur le port ${port}`);
    });

  # 2. La configuration Nginx (qui écoute sur 8080 et renvoie vers Node.js sur 3000)
  nginx.conf: |
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }