apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: saliou-diop-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: nginx
          image: bitnami/nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            # CORRECTIF : On monte tout le volume directement sur le dossier /app
            - name: web-content
              mountPath: /app
            # On laisse le fichier de configuration Nginx à sa place
            - name: web-content
              mountPath: /opt/bitnami/nginx/conf/server_blocks/my_server.conf
              subPath: my_server.conf
      volumes:
        - name: web-content
          configMap:
            name: nginx-config