apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-firewall
  namespace: saliou-diop-dev
spec:
  runStrategy: Manual
  dataVolumeTemplates:
    - metadata:
        name: image-fedora-firewall
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              # On garde 5Gi pour ne pas exploser ton quota Sandbox
              storage: 5Gi 
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm1-firewall
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: boot
              disk:
                bus: virtio
              bootOrder: 1
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      tolerations:
        # Cette règle est souvent obligatoire sur OpenShift Sandbox
        - effect: NoSchedule
          key: sandbox-cnv
          operator: Exists
      volumes:
        - name: boot
          dataVolume:
            name: image-fedora-firewall
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: firewall
              user: fedora
              password: "Password123!"
              chpasswd: { expire: False }
              ssh_pwauth: True