apiVersion: cdi.kubevirt.io/v1beta1
# ... (Garde la partie DataVolume identique)
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-firewall
  namespace: saliou-diop-dev
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm1-firewall
    spec:
      domain:
        devices:
          disks:
            - name: boot
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            # On utilise une seule interface standard
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 1Gi
            cpu: 1
      networks:
        # Connecté au réseau par défaut d'OpenShift
        - name: default
          pod: {}
      volumes:
        - name: boot
          dataVolume:
            name: image-fedora-firewall
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: firewall
              user: fedora
              password: "Password123!"
              chpasswd: { expire: False }
              ssh_pwauth: True
              # On laisse le DHCP d'OpenShift faire son travail, plus de runcmd nmcli !