apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: image-fedora-firewall
  namespace: saliou-diop-dev
spec:
  source:
    http:
      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm1-firewall
  namespace: saliou-diop-dev
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm1-firewall
    spec:
      domain:
        devices:
          disks:
            - name: boot
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: wan
              masquerade: {}
            - name: lan
              bridge: {}
        resources:
          requests:
            memory: 1Gi
            cpu: 1
      networks:
        - name: wan
          pod: {}
        - name: lan
          multus:
            networkName: saliou-diop-dev/reseau-lan
      volumes:
        - name: boot
          dataVolume:
            name: image-fedora-firewall
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: firewall
              user: fedora
              password: "Password123!"
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - nmcli connection add type ethernet ifname eth1 con-name lan ipv4.method manual ipv4.addresses 192.168.10.254/24
                - nmcli connection up lan
                - echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
                - sysctl -p