apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: saliou-diop-dev
data:
  index.html: |
    <!DOCTYPE html>
    <html><body><h1>Bienvenue sur mon Projet !</h1><p>Serveur Nginx conteneurisé et sécurisé pour OpenShift 🚀</p></body></html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: saliou-diop-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx
          # 1. On utilise l'image Nginx officielle sans droits root
          image: nginxinc/nginx-unprivileged:alpine
          ports:
            # 2. On écoute sur le port 8080 au lieu de 80
            - containerPort: 8080
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: web-content
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: saliou-diop-dev
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-route
  namespace: saliou-diop-dev
spec:
  to:
    kind: Service
    name: web-service
  port:
    targetPort: 8080