name: Déploiement OpenShift
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: redhat-actions/oc-installer@v1
        with:
          oc_version: 'latest'
      - name: Connexion OpenShift
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }} --insecure-skip-tls-verify=true
          oc project saliou-diop-dev
      - name: Déploiement Réseau
        run: |
          echo "🌐 Application des politiques de sécurité..."
          rm -f reseau/nad-*.yml reseau/nad-*.yaml || true
          oc apply -f reseau/
      - name: Déploiement Conteneur Web
        run: oc apply -f conteneur/
      - name: Déploiement VM1 (Passerelle/Firewall)
        run: oc apply -f machines-virtuelles/vm1-passerelle/
     # - name: Déploiement VM2 (Base de données)
      #  run: oc apply -f machines-virtuelles/vm2-serveur-bdd/